### ISSUE TITLE
No projects impacted comment appended multiple times

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#1094]
Reported by user A.T.

**Comment by chvima** [comment]
+1
I have switched to using digger via Github Application (and workflow_dispatch in digger) and I'm also getting lot of spam with "No projects impacted". It seems like Github Application is triggered after every:
- label
- comment
- maybe even request review?

Is this configurable?
Ideally to run only on:
- commits
- comments "digger apply" "digger plan"

My workaround is to "disable" the Application and use workflow with custom configuration on pull_request and on issue_comment with conditions, but that's not ideal.

**Comment by ZIJ** [comment]
Again reported today by a different user (M.U.)

**Comment by ZIJ** [comment]
Addressed in #1136

There should now be much less "no projects impacted" comments.

- Comments that do not start with "digger" ignored
- PR events that have no impacted projects do not trigger any messages
- "Digger starting..." comment is only appended in case there are impacted projects

**Comment by chvima** [comment]
Thanks! Tested a few events and it looks clean now.
