### ISSUE TITLE
Drift-detection mode isn't paying attention to the `aws_role_to_assume` config

### ISSUE THREAD

**Issue by UtpalJayNadiger** [diggerhq/digger#1133]
User Feedback:

>Running in drift-detection mode does not assume an AWS role so drift-detection is failing for me currently.

From user K.B

**Comment by JoshuaJackson-jobvite** [comment]
If reading this correctly for this one:
https://github.com/diggerhq/digger/blob/622f43a008901edf60f3fe432d3baf01acd5ff69/cli/cmd/digger/main.go#L259-L273

We're creating the job definition but we don't appear to be passing on the per job behavior the
```
		StateEnvProvider:   
		CommandEnvProvider: 
```

Looking a bit further at the scoped info we have in projectConfig. Per project definition in the projects we would have: 	AwsRoleToAssume    *AssumeRoleForProject

which is a pointer to 

```
type AssumeRoleForProject struct {
	State   string
	Command string
}
```

Ultimately we need to get the right info for the stateenvProvider and commandenvprovider, and from others we see that its a call:

```
GetProviderFromRole(<string>)
```

So would this be as simple as

```

StateEnvProvider: GetProviderFromRole(projectConfig.AwsRoleToAssume.state)
CommandEnvProvider: GetProviderFromRole(projectConfig.AwsRoleToAssume.state)
```
with requisite import for the aws?

**Comment by JoshuaJackson-jobvite** [comment]
certian there's a reason for it, but for mutli project work/behaivors there is also  orchestrator.JsonToJob(job) which would add/include the needed behaviors/properties, and its not used in the manual or drift sections. Design decision?
