### ISSUE TITLE
Only run apply if PR is mergeable

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#118]
Is it possible to allow the digger apply comment to execute only if the PR is currently mergeable?  (i.e.  approved when approvers are mandatory, and possibly up to date with the base branch when required,  etc..)

In Atlantis:  https://www.runatlantis.io/docs/command-requirements.html#mergeable

Thx @fleroux514 for suggesting this!

**Comment by fleroux514** [comment]
@motatoes I can take a look at this

**Comment by motatoes** [comment]
Thanks @fleroux514 I just assigned it to you!
