### ISSUE TITLE
Jobs with orchestrator not picking up custom workflow commands

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#1187]
Example: https://github.com/motatoes/test-digger-workflow-run-steps/actions/runs/7977161282

expecting to see a "I WAS PLANNED" workflow as per the custom workflow but instead not seeing any messages

Meanwhile if I use normal workflow with action events I can see that the custom workflow is picked: https://github.com/motatoes/test-digger-workflow-run-steps/actions/runs/7977445612/job/21780338972

**Comment by motatoes** [comment]
@chvima yes should be! Released in the most recent version so you can test it out :) if you confirm I will close this issue

**Comment by mannemanusha** [comment]
workflows:
  lambda:
    apply:
      steps:
        - init
        - plan # Plan is not working so we are using below
        - run: terraform plan
        - apply
   With this custom workflow we were able to run the plan before apply.
   tested this in digger version 0.4.13.. works fine. thanks @motatoes

**Comment by motatoes** [comment]
In that case I'm closing the issue 💯
