### ISSUE TITLE
Docs on authenticating with OIDC on AWS contain wrong ARN

### ISSUE THREAD

**Issue by haraldsk** [diggerhq/digger#1211]
https://github.com/diggerhq/digger/blob/a37bdcb33e3e13fa1d57f465ab480a7c38a7b0e7/docs/cloud-providers/authenticating-with-oidc-on-aws.mdx#L35

Took me hours to figure this out since I had copy & pasted from this doc:

Wrong: **aws-role-to-assume: arn:aws:sts::{AccountID}:assumed-role/{RoleName}/{FunctionName}**
Right:  **aws-role-to-assume: arn:aws:iam::{AccountID}:role/{RoleName}**

Reference doc on `aws-actions/configure-aws-credentials@v4` usage here: https://github.com/aws-actions/configure-aws-credentials/tree/main?tab=readme-ov-file#oidc-audience

**Comment by motatoes** [comment]
@haraldsk thanks for flagging! Care to submit a PR with this change?

**Comment by haraldsk** [comment]
@motatoes Done, the first PR mentioned was a pebcak, the last goes to the correct repo.
