### ISSUE TITLE
0.4.17 release tag is duplicated

### ISSUE THREAD

**Issue by luong-komorebi** [diggerhq/digger#1404]
This makes it impossible to use the latest release without tagging it twice 

Reference: https://github.com/diggerhq/digger/releases/tag/v0.4.17v0.4.17
![30086](https://github.com/diggerhq/digger/assets/15828926/75bef29e-81b4-4f69-a3a5-1e03a0770f10)

**Comment by motatoes** [comment]
Oh shiz, late night releasing causes such mistakes, I'm going to repeat this release 🙃

**Comment by motatoes** [comment]
Here we go! https://github.com/diggerhq/digger/releases/tag/v0.4.17
