### ISSUE TITLE
Support local cli invocation

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#141]
bumped request from [@daanbosch](https://github.com/daanbosch)

As a user I want to be able to invoke the cli locally within the context of a digger-configured repository and I should be able to run plan and apply commands

Considerations:
- What access controls will this user be given?
- How will access be given to the cli? User provides access or remote job execution (some users don't want to depend on remote workers and would like the ability to execute terraform commands locally)

**Comment by Spartakovic** [comment]
do we still want this to revolve around pull request? like locking, commenting or stuff? do we still want to enable collaboration?
I presume yes, otherwise people can just run terraform commands locally?

**Comment by ZIJ** [comment]
Same as #219

**Comment by ZIJ** [comment]
Closing in favour of #219
