### ISSUE TITLE
Orchestrator is not using jobtype in report title  

### ISSUE THREAD

**Issue by raouf-xh** [diggerhq/digger#1513]
In v0.4.35, the orchestrator is not using jobtype in report title (Plan, Apply)
![image](https://github.com/diggerhq/digger/assets/128371206/4cce6103-18c1-46a5-b1f3-db8ae298eb28)

**Comment by motatoes** [comment]
Thanks for reporting !

**Comment by motatoes** [comment]
Should be fixed in the next release!
