### ISSUE TITLE
SIGSEGV error when defining projects in digger.yml and making a change

### ISSUE THREAD

**Issue by fleroux514** [diggerhq/digger#158]
See the Action triggered by https://github.com/diggerhq/francios-tests/pull/9

https://github.com/diggerhq/francios-tests/actions/runs/4797894917/jobs/8535454961
```
Lock provider has been created successfully
2023/04/25 13:13:22 Following projects are impacted by pull request #9
project_a_d
GitHub event processed successfully
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe3cbc4]

goroutine 1 [running]:
digger/pkg/digger.ConvertGithubEventToCommands({0x1046c80?, 0xc000526050?}, {0xc000526af0, 0x1, 0xc000478cc0?}, 0x2?)
	/home/runner/work/_actions/diggerhq/digger/main/pkg/digger/digger.go:212 +0x9a4
main.main()
	/home/runner/work/_actions/diggerhq/digger/main/cmd/digger/main.go:81 +0x7e6
```

**Comment by fleroux514** [comment]
The root cause is that my declared custom workflow in digger.yml was missing the `workflow_configuration`
i.e.  https://github.com/diggerhq/digger/blob/main/pkg/terraform/utils.go#L119-L122

When declaring custom workflows, default values should be used for `plan`, `apply` and `workflow_configuration` keys when they are not defined.

**Comment by Spartakovic** [comment]
https://github.com/diggerhq/digger/pull/167/files
unfortunately bundled two different fixes into 1 PR
