### ISSUE TITLE
Support of backend-config option in action 222

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#16]
For supporting deployments to multiple environments users need to be able to specify a `-backend-config` option which is passed to `terraform init` command, in this command they will be able to specify which bucket or remote state location as well as state file they will be using. This will unlock all kinds of workflows such as apply to prod on merge (apply to dev on PR), multiple states and so on ..

**Comment by motatoes** [comment]
This will be supported in #100

**Comment by ZIJ** [comment]
Closing because #100 is merged
