### ISSUE TITLE
Does Digger works on GitHub Enterprise Cloud

### ISSUE THREAD

**Issue by gkumarchilakala** [diggerhq/digger#1606]
Hi Folks,

Can you let me know if digger community edition will work for the GitHub Enteprise Cloud, which is cloud based but locked for specific enterprises.

**Comment by UtpalJayNadiger** [comment]
Hey @gkumarchilakala - thanks for creating this issue!

Private VCS support is currently only supported in the enterprise tier, but we'd love to learn your requirements/enable a trial if you're interested. 

Would you be open to booking a call? [Here](https://calendly.com/diggerdev/diggerdemo) are some slots that work for us.

Closing this issue for now - feel free to book a demo/reach out on [slack](https://bit.ly/diggercommunity) for more info!
