### ISSUE TITLE
Digger no runs issue | Digger Github Locking Issue - #1669

### ISSUE THREAD

**Issue by EfeUK** [diggerhq/digger#1677]
We had the locking issue earlier this week, the ticket 1669 has been closed, indeed the lock issue no longer occurs. However we are unable to perform any runs - plan and apply. (digger plan).

When we do nothing happens. Please assist thanks. 
![Screenshot 2024-08-23 at 11 14 48](https://github.com/user-attachments/assets/c8e9b161-728c-4216-8d5d-dedd5c0c154f)

**Comment by motatoes** [comment]
hi @EfeUK please join our slack via digger.dev and chat with us in #support so we can debug this issue

**Comment by EfeUK** [comment]
Hi @motatoes , ok to close, it is working for us again.
