### ISSUE TITLE
'Workspace "default" already exists' error when making a change to a project configured with digger.yml

### ISSUE THREAD

**Issue by fleroux514** [diggerhq/digger#168]
Reproduced with https://github.com/diggerhq/francios-tests/pull/9

https://github.com/diggerhq/francios-tests/actions/runs/4798029175
![image](https://user-images.githubusercontent.com/17277004/234313706-0d5a8c58-32e5-49cf-be86-f9c7e6ecf80f.png)

**Comment by Spartakovic** [comment]
https://github.com/diggerhq/digger/pull/167/
