### ISSUE TITLE
implement digger help command

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#18]
show what are the possible commands to use when user comments `digger` or `digger help` or another incorrect digger command

**Comment by veziak** [comment]
"help" and "version" for a start

**Comment by motatoes** [comment]
digger help

```
Use the following commands to get started:

digger version: Show digger version
digger plan:
digger apply: 
digger unlock: 
```

digger version

```
Using digger version 0.2.1
```

Version can be hardcoded as a constant for now and we will bump it for every release
