### ISSUE TITLE
Terragrunt versions 0.67.0+ break plan output

### ISSUE THREAD

**Issue by ben-of-codecraft** [diggerhq/digger#1814]
Newer versions of Terragrunt will cause plans to hot show up see screen shot here: 

![image](https://github.com/user-attachments/assets/8b81729e-2b26-4b9c-9996-552156fc077a)

This looks to be related to the `cleanupTerraformOutput` in execution.go expecting a different format of log output for Terragrunt, which was changed in 0.67.0+ 
https://github.com/gruntwork-io/terragrunt/issues/3367

In order to have the logs look like they used to the following additional environment variables must be passed into the command. 
https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-forward-tf-stdout

It looks like a new flag needs to be added but conditionally on version upgrade.  Not sure I agree with them not making that a 1.0.0 release as it seems breaking to things like digger.

**Comment by motatoes** [comment]
I fixed this issue in the most recent release of digger

**Comment by motatoes** [comment]
It's fixed in this PR https://github.com/diggerhq/digger/pull/1801

**Comment by ben-of-codecraft** [comment]
oh crap awesome
