### ISSUE TITLE
Possibility to unlock project on PR merge instead of apply command

### ISSUE THREAD

**Issue by fleroux514** [diggerhq/digger#185]
Right now a project is unlocked as soon as the apply cmd succeeded.

I'm thinking this might be problematic when the PR affects more than one project and
- user applies changes on one specific project  (`digger apply -p xxx`)
- user runs `digger apply` but some projects fail and some succeed.

This might leave some projects with a temporary drift since their state file is not in sync with the code, and allows new PRs to grab the lock and possibly get merged  before the original PR is merged into main.

**Comment by Spartakovic** [comment]
now I am thinking, maybe default behaviour is actually not to unlock on merge. What do you think @fleroux514 ? As far as I understand atlantis only unlock in case of closed/merged PR, doesn't do anything on apply

**Comment by Spartakovic** [comment]
yeap, that sounds good to me @fleroux514
