### ISSUE TITLE
Volunteer 

### ISSUE THREAD

**Issue by momomuchu** [diggerhq/digger#283]
I saw on reddit that someone was searching a contributor so im in for adding features and stuff

**Comment by ZIJ** [comment]
That true! What'd you like to work on most?

**Comment by momomuchu** [comment]
to be honest i haven’t really read the code that much so could you just give me task and i’ll do it

**Comment by ZIJ** [comment]
@momomuchu please feel free to pick up anything that has "help wanted" or "good first issue" label

We have extremely limited coordination capacity so have to rely on contributors to pick tasks according to their liking. The most we can do is label what needs to be done with tags

I am going to close this issue for now
