### ISSUE TITLE
Drift detection

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#297]
Currently Digger does neither provide drift detection, nor facilitates it

Approach suggested by Karl Taylor @ Bitmex: ability to run a cron-like job to check for drift with smth like driftctl

**Comment by fleroux514** [comment]
Will give it a shot

**Comment by motatoes** [comment]
@fleroux514 has pushed his initial implementation to branch on drift as well 

https://github.com/diggerhq/digger/commits/feat/add-drift-detection-support

**Comment by ZIJ** [comment]
With the introduction of an orchestrator the approach will likely need to change somewhat - but to the better. We'd no longer be limited by Github Actions API and can be consistent across multiple CI providers.

**Comment by ZIJ** [comment]
Closing in favour of #715
