### ISSUE TITLE
error " PR is not mergeable. Status: pending"

### ISSUE THREAD

**Issue by frank-bee** [diggerhq/digger#299]
Lock provider has been created successfully
2023/05/26 12:35:05 Following projects are impacted by pull request #630
GitHub event processed successfully
GitHub event converted to commands successfully
2023/05/26 12:35:05 Following commands are going to be executed:
2023/05/26 12:35:05 PR is not mergeable. Status: pending
Error: Process completed with exit code 1.

**Comment by frank-bee** [comment]
Hi @motatoes , this is not reproducible, I close the issue.
Thanks for looking at it!

**Comment by fleroux514** [comment]
Just reproduced this issue by pushing a commit which is updating my Github workflow file to use Digger v0.1.22 and making changes in digger.yaml.

So there are no changes in the projects themselves, and seems like the logic is trying to merge the PR in that case.

https://github.com/diggerhq/francios-tests/actions/runs/5155590055/jobs/9285458344

**Comment by motatoes** [comment]
Thanks for the repo tips @fleroux514 ! got this fixed in https://github.com/diggerhq/digger/pull/312/files and we will add a scenario for this in the next tests indeed
