### ISSUE TITLE
403 Resource not accessible by integration []

### ISSUE THREAD

**Issue by almereyda** [diggerhq/digger#395]
When a workflow run using AWS OIDC federation fails with:

```
error getting pull request: GET https://api.github.com/repos/octo-org/octo-repo/pulls/1/files: 403 Resource not accessible by integration []
```

we need to explicitly add `pull-request: write` `permissions:` as such:

```diff
  permissions:
    id-token: write
    contents: read
+   pull-requests: write
```

—

### Reference

* [GitHub Actions - Resource not accessible by integration](https://sjramblings.io/github-actions-resource-not-accessible-by-integration?x-host=sjramblings.io)

**Comment by ZIJ** [comment]
Thanks for filing @almereyda ! we will look into this asap

**Comment by almereyda** [comment]
Thank you for looking into this.

OIDC is used implicitly with `aws-role-to-assume`.

The article linked in the OP references section described the same observed behaviour under very similar circumstances, using AWS "workload identity", and the fix helped.
