### ISSUE TITLE
Handle timezone in comment report

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#440]
> The report time seems to be GMT. Is is expected? ... I would suggest at least adding Z : 2023-07-10 17:48:08Z to make it explicit.

Reported by @fleroux514

**Comment by ntguilty** [comment]
if you don't have anyone willing to do it so far, I'd be happy to volunteer :)

**Comment by ZIJ** [comment]
Yes please! That'd help a lot; assigning to you

**Comment by veziak** [comment]
it will be included into the next release v0.1.29
