### ISSUE TITLE
action should install precompiled binaries from github/releases

### ISSUE THREAD

**Issue by airtonix** [diggerhq/digger#445]
so we dont have to wait for golang to download all the deps and run it.

**Comment by ZIJ** [comment]
Thanks for filling! Yes indeed that'd make it much faster

**Comment by Spartakovic** [comment]
it's actually being done already if you use stable version from releases. It only compiles if using a branch like develop

**Comment by airtonix** [comment]
> it's actually being done already if you use stable version from releases. It only compiles if using a branch like develop

Ahh then it's merely a matter of documentation? (or am I just dense?)

**Comment by Spartakovic** [comment]
ah yeah, it's just a matter of documentation. We can use this issue to update it actually

**Comment by Spartakovic** [comment]
Unless you experience go compiling even using releases, in that case we can have a look at that

**Comment by motatoes** [comment]
hey @airtonix we just updated the docs here to make it more clear, feel free to reopen this issue if you have more context to add! https://docs.digger.dev/configuration/versioning
