### ISSUE TITLE
"terraform init" failures should post failure root cause in the "Digger run report"

### ISSUE THREAD

**Issue by fleroux514** [diggerhq/digger#468]
Just noticed that when "terraform init" fails, the root cause is not posted in the "Digger run report".

Maybe it could be posted under a "Init for [project name]" collapsible comment

![image](https://github.com/diggerhq/digger/assets/17277004/3e2be0f5-9960-4579-a50d-6f26cb60be00)

**Comment by motatoes** [comment]
hey @fleroux514 ! Yes indeed this is a good improvement point for digger 😄 we are on it

**Comment by isaacmcollins** [comment]
Can I take this one? @motatoes 

Something like this?

<img width="842" alt="Screenshot 2023-08-28 at 10 39 06 PM" src="https://github.com/diggerhq/digger/assets/122894610/36998ad1-2b8d-4f32-992e-18145845c7d2">

**Comment by motatoes** [comment]
@isaacmcollins sorry for delayed response! Absolutely go for it , please feel free to submit a PR for this issue :)) The screenshot looks great to me 👌
