### ISSUE TITLE
No report generated when there are no configuration changes

### ISSUE THREAD

**Issue by fleroux514** [diggerhq/digger#501]
While testing with `diggerhq/digger@v0.1.30`, noticed that no report was generated when there were no infrastructure changes.

**Comment by fleroux514** [comment]
https://github.com/diggerhq/francios-tests/actions/runs/5859763324 was triggered from my `fix` commit:

![image](https://github.com/diggerhq/digger/assets/17277004/e6771f84-73b9-4650-8773-c6ea4085183c)

In PR:  https://github.com/diggerhq/francios-tests/pull/37,  no generated report

![image](https://github.com/diggerhq/digger/assets/17277004/808cda3d-6ccd-4dd4-9acf-8978cb89902b)

**Comment by motatoes** [comment]
Thanks for reporting! Probably a sideeffect of some recent change we will take a look and fix it for the next release
