### ISSUE TITLE
User nonroot commands while installing GH action

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#505]
User reported from slack:

    Hi. I just tried running digger and stumbled over this line which produces an error in my workflow: 
    https://github.com/diggerhq/digger/blob/15ccff47be4602502cd98b55922e751f79610224/action.yml#L247. Is this action 
    supposed to run as user root? The path is usually not accessible as a regular user and running just everything as root 
    seems awefully weird.

Proposed solutions are:

- appending `sudo` to the mv command to make sure it is run as previlliged user
- instead of using a mv command to append it to `$PATH` variable however still not sure if this will be correctly properly propagated in custom workflows

**Comment by veziak** [comment]
it should be fixed in the next release
