### ISSUE TITLE
Digger apply always creates a new plan an applies it

### ISSUE THREAD

**Issue by joerg** [diggerhq/digger#553]
Working with digger I realized that any "digger apply" comment will always create a new plan and apply that one. No matter if a plan already exists.

Steps to reproduce:
* Run a digger project
* Create a PR
* Optional (approve the PR)
* Comment "digger apply" -> This will directly apply creating a new plan
* Comment "digger plan"
* Comment "digger apply" -> Check the action logs and a new plan will appear

**Comment by joerg** [comment]
Looking closer at the action definition there is no plan download step before running digger/terraform apply. This means that currently digger does not guarantee the integrity of what is reviewed to what is applied. I think this is a pretty serious issue and should be priorized.

**Comment by joerg** [comment]
Since this issue really bugs me out I had a look at the code and `-auto-approve` is hardcoded there: https://github.com/diggerhq/digger/blob/develop/pkg/core/terraform/tf.go#L106

**Comment by motatoes** [comment]
I confirmed this issue in my setup too and we are working on the fix now

**Comment by Spartakovic** [comment]
fixed in https://github.com/diggerhq/digger/pull/610, will be included in the next release
