### ISSUE TITLE
Support merge-before-apply strategy

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#56]
Opinions differ on this; see [merge-apply dilemma](https://itnext.io/pains-in-terraform-collaboration-249a56b4534e)
- Some prefer to iteratively apply on a branch, then merge once
- Others prefer to only deploy from main, creating additional fix PRs if apply breaks

Currently the default in Digger is [branch-deploy model](https://github.blog/2023-02-02-enabling-branch-deployments-through-issueops-with-github-actions/)

We might want an additional optional strategy to support apply-on-merge

**Comment by motatoes** [comment]
This was supported in #48 but needs better documentation and to support several usecases
