### ISSUE TITLE
Support OIDC for Azure

### ISSUE THREAD

**Issue by sat0ken** [diggerhq/digger#569]
Currently, CLIENT_SECRET environments variables is required for login to Azure. 

https://github.com/diggerhq/digger_azure_demo/blob/main/.github/workflows/plan.yml

I think It might be a good idea to able to login with OIDC same as AWS and GCP.

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure

**Comment by motatoes** [comment]
hey @sat0ken that's a great suggestion! We need to improve our azure suport indeed and include OIDC.
