### ISSUE TITLE
Digger logs secrets from state

### ISSUE THREAD

**Issue by krzwiatrzyk** [diggerhq/digger#580]
Hi,

I am using terraform to create AWS IAM Access Keys and I can see that digger displays that in the log (that huge JSON object displayed after plan). 

Is there a way to stop Digger from displaying that?

**Comment by motatoes** [comment]
Hey @krzwiatrzyk thanks for reporting this! It has been fixed in #552 and will be reased in v0.1.32 next week ..

If you want to try it right now you can try to use @v0.1.32-pre in your test and it should no longer display that json blob

**Comment by krzwiatrzyk** [comment]
I can confirmed it's fixed, thanks!
