### ISSUE TITLE
Version should not be constant?

### ISSUE THREAD

**Issue by kevinmichaelchen** [diggerhq/digger#581]
I'm packaging up the CLI for https://tea.xyz.

https://github.com/teaxyz/pantry/pull/3358

It appears the `version` is hard-coded as 0.1.6 [here](https://github.com/diggerhq/digger/blob/v0.1.31/pkg/utils/version.go#L5).

If that is changed from `const` to `var` then `ldflags` should be able to access it.

**Comment by motatoes** [comment]
Hey @kevinmichaelchen thanks for integrating it .. I'm not familiar with tea package manager but this file is outdated  (needs to be fixed actually to pick it up dynamically) .. we currently rely on github tags for publishing the version number. Could you share what would help you include digger into the package manager ?

**Comment by kevinmichaelchen** [comment]
Hey @motatoes - everything is actually building just fine in this PR:

https://github.com/teaxyz/pantry/pull/3358

The only small issue is that `version` needs to be a `var` instead of a `const` — per this [ldflags discussion](https://github.com/golang/go/issues/22706).

**Comment by kevinmichaelchen** [comment]
> okay! Do you expect that every release needs to update that version as well? Because currently this value isn't being incremented by us so we need to find a way to auto increment it on our side to match your requirements

@motatoes — I think something like this would work?

https://github.com/diggerhq/digger/pull/584/files
