### ISSUE TITLE
Repository is too big

### ISSUE THREAD

**Issue by hasafox** [diggerhq/digger#64]
I'm interested in this project and I forked it and git clone, however it is too big, almost 200 MB in fact, so that I had given up once. I was confused that why so big it is, and I run command below:

```shell
git rev-list --objects --all | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' | awk '/^blob/ {print substr($0,6)}' | sort --numeric-sort --key=2 | cut --complement --characters=13-40 | numfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
``` 

And I found there are 3 files not used now but in git commit log.
![image](https://user-images.githubusercontent.com/36329819/227541269-d6a3062d-8fc7-40b0-a3a7-e775ed47838b.png)

Perhaps the team is not very familiar with Git, but a large repository can prevate many interested individuals from cloning it. Hope maintainers can remove these unnecessary files at once and make it easier to git clone.

**Comment by motatoes** [comment]
Hello @hasafox thank you for reporting this! Indeed we had pushed these binaries in an earlier version and removed them after migrating to golang. we will be removing these files and pushing in order to rewrite the history

**Comment by motatoes** [comment]
It's done now, should be back to <1MB size
