### ISSUE TITLE
OpenTofu support in digger

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#736]
It has been requested to support OpenTofu in digger. From my prespective it should be a very straightforward implementation especially since OpenTofu and terraform have identical CLI API. Here is what needs to be done within digger to support opentofu:

- Implementation of OpenTofuExecutor interface which implements the same interface as [`TerraformExecutor`](https://github.com/diggerhq/digger/blob/875c375f9aed767192a0a476542e914d898ae18b/pkg/core/terraform/tf.go#L13)
- Expose a `setup-opentofu: true` option in the action.yml composite similar to what was done for terraform and terragrunt. It will install openTofu using [official action](https://github.com/opentofu/setup-opentofu)
- support an additional argument of "opentofu: true` in digger.yml. This will be used to pass the appropriate executor in the [job for example here](https://github.com/diggerhq/digger/blob/d8c97bac74d1549721d3656e994a0b531d972276/pkg/digger/digger.go#L434)

**Comment by kvendingoldo** [comment]
btw. you can also integrate [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management.
