### ISSUE TITLE
Support more lock providers

### ISSUE THREAD

**Issue by ynden** [diggerhq/digger#75]
`digger` currently supports  DynamoDB for locks. However, in Azure DynamoDB service doesn't exist (there's a CosmosDB, but not the same schema).

A more native way in Azure would be to use a Storage Account. Actually the same storage account where the terraform state is kept. We would rely on Storage Account table to store our lock.

But before that, we need to adjust the codebase to start using multiple cloud providers.

* Start using a LockService struct
* Add CloudLock interface as property

Then instead of using DynamoDB directly, we'll call LockService which will rely on the underlying CloudLock provider.
The right lock provider will be injected when creating a LockService.

Example of implementation, check below
```go
// Add the right param and return type
type CloudLock interface {
	Lock()
        Unlock()
        ForceUnlock()
}
```
The Lock Service:

```go
type LockService struct {
	lockProvider CloudLock
}

func (ls *LockService) Lock() {
    return ls.lockProvider.Lock()
```

StorageAccount in Azure, implementation example:
```go
type StorageAccountLock struct {
}

func (sal *StorageAccountLock) Lock()  {
	// add table with data to storage account
}
```

Full workflow (kept easy to be readable):

```go
//Detect cloud vendor (or will be defined in digger.yaml)
lockVendor := getLockVendor(&config)
var cloudLock CloudLock

// Use switch or if/else
if lockVendor == "azure" {
    cloudLock := cloudLock.(StorageAccountLock)
}

if lockVendor == "aws" {
     cloudLock := cloudLock.(DynamoDBLock)
}

lockService := LockService {
    lockProvider: cloudLock
}
lockService.Lock()
```

**Comment by Spartakovic** [comment]
There is already a Lock interface pkg/utils/locking

**Comment by motatoes** [comment]
Thank you for this detailed issue and outlining refactoring steps @ynden. All looks good here, looking forward to reading your PR

**Comment by motatoes** [comment]
performed in a separate branch and will be merged gradually into mainline as we restructure bits and peices
