### ISSUE TITLE
Expose lower level CLI API

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#754]
Digger currently is invoked as a cli within CI jobs. The following outlines the lifecycles of a digger run:

- `digger` cli invoked within CI job
- Digger detects CI and parses SCM event metadata to identify the event type and metadata such as files changed and event owner
- Digger reads digger.yml
- digger identifies the commands that need to be run
- digger checks for OPA access policies if any exist
- Digger executecutes the commands
- Digger performs plan policy checks
- Digger interacts with the SCM to perform output actions such as commenting, update of status checks or PR merging, according to configuration in digger.yml

Due to this sequence of commands the support of more SCM and CI systems beyond github+github Actions means that digger needs to implement:
- ability to parse payloads from SCM and figure out the actions to take place
- ability to interact with SCM API to perform actions as configured

This is ultimately what needs to happen but it also means that it takes a longer time to support a wider range of CI systems since the combination of possibilties is exponential:

Common SCM requests that we receive:
Bitbucket
Github
Gitlab
Azure Repo
Gitea

Common CI system requests that we recieve:
Jenkins
Azure Devops
Bitbucket cloud
CircleCI
ArgoCD

As a result the number of combinations we need to support is NxM
----

While all these implementations are completed and tested It is proposed to expose a lower level API that handles the core functionality independent of **SCM** and **CI** system, which makes it easier to support basic flows in any CI system:

- digger identifies the commands that need to be run
- digger checks for OPA access policies if any exist
- Digger executecutes the commands
- Digger performs plan policy checks
- [OPTIONAL] support for webhooks post runs so users can compose their own workflows

If we support this lower level then users can quickly integrate into their other CI systems which are not supported by listening for individual events and invoking the digger cil accordingly, for example:

```
digger --event=pullrequest_open --owner=motatoes --files-changed="prod/main.tf"
digger --event=pullrequest_comment --owner=motatoes --body="digger plan --files-changed="prod/main.tf""
digger --event=pullrequest_comment --owner=motatoes --body="digger apply --files-changed="prod/main.tf""
digger --event=pullrequest_merged --owner=motatoes
digger --event=pullrequest_closed--owner=motatoes
```

by default digger will print logs to STDOUT, however it can also be passed a webhook where it send the output payload and the results of its run so that users can create their own custom workflows

**Comment by ZIJ** [comment]
Closing because its done in #1008
