### ISSUE TITLE
Get rid of hardcoded value of bucket for GCP

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#94]
GCP bucket names are globally unique. We assumed that they would not be globally unique. We had hardcoded the value of bucket as `digger-lock` so now we want to instead make the user define it using the environment name directly

if the environment variable is not set and we are using GCP then we throw an error asking the user to set this value GOOGLE_STORAGE_BUCKET

**Comment by fleroux514** [comment]
Hi @motatoes ,

One question I have is: is there a need to create 1 bucket for every project configured in `digger.yaml`?

**Comment by motatoes** [comment]
hey @fleroux514 ! No you only need to create one bucket for all your projects, that will be sufficient for the locks :)

**Comment by fleroux514** [comment]
Thanks!
