### ISSUE TITLE
Aggregate checks for plan / apply separately

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#959]
Currently there are only project-specific checks, which makes it impossible to set up a branch protection rule that wouldn't allow merging unless all projects have successfully ran plan.

> I would like to add branch protection to ensure Plan is performed before any apply.
At the moment, it is quite difficult because of the name of the check.
The check name contains the project name ex: something/plan && something/apply
If we have many projects, it will be difficult to add a branch protection and auto merge at the same time as the branch won’t be mergeable because of missing check

### Proposed solution
(just like in Atlantis)

Have 2 additional aggregate checks:
- "plan", marked successful if and only if every project had at least 1 successful plan at the latest commit of the PR
- "apply", marked successful if and only if every project had a least 1 successful applay at the latest commit of the PR

Reported by user A.T.

**Comment by motatoes** [comment]
This has been implemented on #1150
